### ISSUE TITLE
Plot function prnts output as showing x number of variables, but not actually

### ISSUE THREAD

**Issue by tetul** [andjar/ALASCA#12]
Hello, 

This was an issue I discovered by chance. 

I have my data in the long format, and I have 13 dependent variables. All NAs are omitted from the dataset. 

The model itself runs fine, with no error. 

When I plot the effect plot, it prints "Showing 13 of 13 variables. Adjust the number with `n_limit`"

However, in the loadings plot, there is a variable missing. This is irrespective of what type of plot I'm using to look at the loadings. The variable does not show up on the histogram plot, nor the loadings. 

And it is just one variable, per principal component, and not even the same every time. 

And yes, I have the latest version of the package. 

Happy for any lead! 

![image](https://github.com/andjar/ALASCA/assets/13193540/323f4dbb-b453-407e-923a-c04c66c9931d)

plot(mod1, effect = c(1), component = c(1,2), type = 'effect')
INFO  [2024-05-15 15:46:16] Effect plot. Selected effect (nr 1): `Age`. Component: 1 and 2.
WARN  [2024-05-15 15:46:16] Showing 13 of 13 variables. Adjust the number with `n_limit`
WARN  [2024-05-15 15:46:16] Showing 13 of 13 variables. Adjust the number with `n_limit`

**Comment by andjar** [comment]
Hi @tetul,

Thanks for reporting this issue and for your thorough description. I will look into this in a couple of weeks when my exams are finished!

Best,
Anders

**Comment by andjar** [comment]
Hi @tetul,

Thanks again for reporting this issue. This was indeed a bug where `n_limit` did not work as intended. This is now corrected in v1.0.16 (https://github.com/andjar/ALASCA/commit/83848dd43347eba7f3389500a2e54566953d0c36)

I also increased the default `n_limit` so that you automatically will get all your 13 variables out;)

Please feel free to reach out again if there are other issues!

Best,
Anders
